In [55]:
import numpy as np
h = np.array([1,2,4,4,6,6,7,8,9])
x = np.ones([h[0]])
y = np.zeros((h[1]))
z = np.zeros(h[1])
print("{} {} {}".format(x.shape,y.shape,z.shape))

q = 1/h

print(q)

h = np.zeros((5,2,3,4))

# h1 = np.pad(h, ((0,0),(1,1),(1,1)), 'constant', constant_values=(1))
# h2 = np.pad(h, ((1,1),(0,0),(0,0)), 'constant', constant_values=(1))

print(h1.shape)
print(h2.shape)
print(h)

(1,) (2,) (2,)
[1.         0.5        0.25       0.25       0.16666667 0.16666667
 0.14285714 0.125      0.11111111]
(2, 4, 4)
(4, 2, 2)
[[[[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]

  [[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]]


 [[[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]

  [[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]]


 [[[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]

  [[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]]


 [[[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]

  [[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]]


 [[[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]

  [[0. 0. 0. 0.]
   [0. 0. 0. 0.]
   [0. 0. 0. 0.]]]]


In [9]:
for i in reversed(range(9)):
    print(i)

8
7
6
5
4
3
2
1
0
